### ISSUE TITLE
Crypto JS is blocked by some adblockers

### ISSUE THREAD

**Issue by nk932714** [robinmoisson/staticrypt#107]
Demo Not working on Mozzila firefox 54.0 (32-bit)

**Comment by robinmoisson** [comment]
Everything seems to be working fine on my version (Mozilla 58), can you detail what's happenning? 

Meaning:

1. What exactly did you do (click on button, enter text...)
2. what did you expect to happen
3. what actually happened

Thanks !

**Comment by nk932714** [comment]
![image](https://user-images.githubusercontent.com/29853208/36303431-21bb8cb2-1332-11e8-8429-b8d8942fa23f.png)
when entering the password = test and clicking on DECRYPT button nothing is happening.

**Comment by robinmoisson** [comment]
Strange... Can you open your dev console (Ctrl+Shift+K) and tell me if you see any error message?

**Comment by TotomInc** [comment]
Got the same issue, errors with my adblocked enabled:

![image](https://user-images.githubusercontent.com/9285210/36310053-1ef07138-1327-11e8-87e9-11a2b7f284d8.png)

Looks like CryptoJS get blocked by my ad-blocker extension (uBlock origin) probably because of the name CryptoJS. uBlock think it's another crypto-miner lib for the browser. If you disable your ad-blocker extension @nk932714 it will work fine.

It looks like a serious issue if you use CryptoJS from the CDN though.

**Comment by robinmoisson** [comment]
Good catch @TotomInc and thanks for the debugging, indeed that's an issue.

Do you see what list the block comes from? I contacted the guys from the only ad blocking list with `crypto-js` I found ([no-coin list](https://github.com/hoshsadiq/adblock-nocoin-list/issues/137#issuecomment-366458325)), we'll if they can remove it.

If not (and it might be added to other lists anyway) I see two solutions:

- keep using crypto-js but embed it in the main website and remove the CDN option for the encrypted file
- use the browser's WebCrypto api, then I need to check if browser support is enough and test it (Chrome seems to only allow the API on secure connection, it needs to works when opening local files too)

@nk932714 short term solution (if that is what's causing your issue) is to deactivate your adblocker on the website and on the files you encrypt if relevant. Let me know if that solves your issue.

**Comment by TotomInc** [comment]
I don't know from what list it can be blocked, but there are a tons of different list that everyone can use. This issue should not be resolved this way.

How do you plan to implement it using WebCrypto browser's API? I think this is the right way to implement it without being blocked by extensions.

**Comment by nk932714** [comment]
Thanks @TotomInc 
yes @robinmoisson disabling this adblock  worked for me
![image](https://user-images.githubusercontent.com/29853208/36361260-a1e250ae-1550-11e8-9bc1-06ea232b8aa0.png)

i am using three types of adblock 
- ublock
- adblock ultimate
- adblock plus

it is causing problem only with `adblock ultimate` only

**Comment by robinmoisson** [comment]
Thanks for the info @nk932714, low hanging fruit for now: I serve the `crypto-js` file with a modified name from this repo instead of a CDN. 
This should solve your issue, let me know if you can use the website again!

The problem might still affect people who do not embed the lib into the protected file (then it's served from the public CDN), I changed the defaults but I'm leaving this open.

**Comment by TotomInc** [comment]
It works fine now 👍

**Comment by nk932714** [comment]
Thanks a lot @robinmoisson its working fine now :1st_place_medal:
