### ISSUE TITLE
Passwords that contain </ fail to encrypt

### ISSUE THREAD

**Issue by homepage1** [robinmoisson/staticrypt#109]
Plain text rocks.

**Comment by robinmoisson** [comment]
I can't reproduce, `</123` works as a password in chrome. What browser/password do you use?

**Comment by homepage1** [comment]
Not the Staticrypt password, the string to encrypt (I use it to encrypt my passwords).

**Comment by robinmoisson** [comment]
The text to encrypt is expected to be html, since to decrypt we load it in place of the password prompt original html. So it will try to parse your text as html and if there as html sensitive character that will give garbled results.

What you could do: enclose your password in `<code>` or `<pre>` tag, so that the decyphered text is valid html.

Ex: encrypt

    <pre>
    my</password
    </pre>
