### ISSUE TITLE
curly braces in CLI result in Syntax Error

### ISSUE THREAD

**Issue by patrulea** [robinmoisson/staticrypt#127]
My Yarn project encrypts an HTML after building with Eleventy and SASS with this command:

`"build:encrypt": "find ./_site/wip -type f -name '*.html' -exec staticrypt {} morpho -o {} -f ./password.html \\;"`

Though, it mysteriously started printing this message when I moved from npm to Yarn:

`Syntax Error: Expected "$", "$'", "$(", "$((", "${", "&", "&&", "'", ";", "<", "<&", "<<<", ">", ">&", ">>", "\"", "\"\"", "\\", "|", "|&", "||", [ \t], [0-9], or end of input but "{" found (line 1, column 58).`

Column 58 in this command corresponds to the first opening curly brace `{`.

It used to work fine a couple months prior and I can’t find much info on this error.

**Comment by patrulea** [comment]
That did solve the syntax issue! Thank you.

Maybe in the future, `staticrypt` could implement a native way to encrypt multiple files at onces.

**Comment by patrulea** [comment]
This is odd. I eventually went back to NPM to make use of the `pre*` and `post*` build commands; now `staticrypt` runs all fine. Though, the protected page would not decrypt with the password I set up (`tiliche`) with this command:

`find _site/wip -type f -name '*.html' -exec staticrypt {} tiliche -o {} -f password.html \\;`

The protected page is up on this Netlify deploy: https://626195be51b47b000800dcf1--los-hopper.netlify.app/wip/

This is my repo: https://github.com/patrulea/los-hopper

**Comment by robinmoisson** [comment]
Thanks for linking to your repo - you're using staticrypt 2 but your custom password template is using the v1 way of decrypting, that's why it's not working.

There was a breaking change in Staticrypt 2 (you can check the [release notes](https://github.com/robinmoisson/staticrypt/releases/tag/v2.0.1)) that handle the salt generation differently, now the salt needs to be injected into the template at encryption time (this is to support the "remember me" checkbox, which allows among other things to encrypt multiple pages on a single domain and have to enter the password only once to decrypt all pages).

To fix this, you can either change your package.json to fix staticrypt version to `1.x` or update your custom template to handle the new way of decrypting the page.

**Comment by patrulea** [comment]
I really appreciate your help, Robin.

I downgraded to `1.4.1` and everything runs as intended!
