### ISSUE TITLE
[Request] Forget checkbox

### ISSUE THREAD

**Issue by cepreu5** [robinmoisson/staticrypt#152]
~~It will be useful to add a visual representation of the *mysite.com?staticrypt_logout* option when *Default: "0", no expiration* was selected (the default case).~~

~~When checked, the *clearLocalStorage()* function will be executed on form submission.~~

Please, ignore this, my custom template always shows logon part, even when there is remembered password.

**Comment by cepreu5** [comment]
Closed!

**Comment by robinmoisson** [comment]
Hey @cepreu5, glad if your problem is solved, thanks for updating the issue!

That resolution is surprising to me - if you check the "remember-me" checkbox you should not see the login page unless localStorage is cleared or the remember-me expires.

That's why I don't see another option than manually adding `?staticrypt_logout` to the URL: since we don't get to see the login page anymore because it decrypts automatically, we can't show any button to the user. Staticrypt doesn't add a navbar to the decrypted page with a logout button like regular websites do, so I don't see another solution.

Good if the problem is solved for you, feel free to re-open if you find you need additional help on that issue.
