### ISSUE TITLE
Question - Is it possible to still use CryptoJS?

### ISSUE THREAD

**Issue by AwesomeCaden73** [robinmoisson/staticrypt#180]
Long story short, I've been using this to distribute files meant to be view locally, rather than on a server. CryptoJS, it's embeddable nature, and the fact that it doesn't require HTTPS served my purposes perfectly - but the forced move to WebCrypto has effectively broken everything. Even version 2 doesn't work anymore.

Is there any way to revert to the original system?

P.S. it seems that the embed cryptojs checkbox on 2.x has disappeared... server strangeness?

**Comment by AwesomeCaden73** [comment]
Nope, I was right... Version 2, the CryptoJS-based version, is completely broken. 

Functionality is extremely inconsistent (it worked once or twice, but not the rest of the time)

When I attempt to encrypt something using version two, either the login page doesn't load at all (showing only a loading circle and a page title of "/*[|template_title|]*/0", or if it does load, then the decrypt button does nothing except trigger an empty alert().

I uploaded an example of a functional and nonfunctional page:
[examples.zip](https://github.com/robinmoisson/staticrypt/files/11489567/examples.zip)

P.S. Whatever happened to the "embed cryptoJS" option?

**Comment by robinmoisson** [comment]
Hey @AwesomeCaden73 , thanks for reporting!

So were all those issues fixed by the folder renaming? If so I don't really have a lead on why, except I assume some weird cache somewhere...

I do want to keep supporting v2 since it's the only way to use HTTP, so feel free to open issues regarding that version if you find any bugs. Also in your case: if you're viewing the files locally browsers usually consider `file://` [to be a secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure), so WebCrypto should work on local files as well.

**Comment by drzraf** [comment]
If you consider the impossibility to use the crypto API inside "non-secure" webcontext as a problem, here is a place to voice/thumb-up : https://github.com/w3c/webappsec-secure-contexts/issues/104
