### ISSUE TITLE
Auto remember me from shareable link

### ISSUE THREAD

**Issue by uzadude** [robinmoisson/staticrypt#183]
This is an amazing project!

Would like to suggest an option to auto enable the "remember me" when using the shareable link .

With that users would need to use the "ugly" link only once, and from there on the readable link.

**Comment by uzadude** [comment]
Hi,
yup, it's related to what you wrote in the last sentence.
Our use-case is documentation site based on docusaurus (react) which indeed has many pages. The experience we want to give to our customers is basically that they will not even be aware that it is an encrypted site. they will just click the link once, and from there on they will be able to freely navigate between the pages and even share links (without the hashed-password)
with one another.

**Comment by robinmoisson** [comment]
I think that makes sense, though maybe unusual for share links, since encrypting multiple pages is a common use case.

Thanks for the suggestion!

**Comment by samibkf** [comment]
Hello @robinmoisson  & @uzadude ,  I really need the shareable link auto-remember feature.
If it's already implemented, I'd be grateful if you could point me towards how to use it!

**Comment by uzadude** [comment]
@samibkf - we ended up using a patch (with `patch-package`) with the contents of #184 and it works great.

**Comment by robinmoisson** [comment]
Woops sorry, looks like time flew faster than I noticed. This is now a feature of version 3.4.0 that has just been pushed to npm - you can add `&remember_me` to your sharable link, or add the `--share-remember` flag to you command to get the link, as is now documented in the readme.

@uzadude the hashed password is preferred in the url fragment rather than query params (`#staticrypt_pwd=...` rather than `?staticrypt_pwd=...`) to avoid sending it to the server since it's only needed client-side. We still support query param for backward compat reason, so I added support for the `remember_me` to be passed in query param too like you did, so it should be backward compatible with your patched version as well. :slightly_smiling_face: 

https://github.com/robinmoisson/staticrypt/blob/1e5e6cf7dd4054749b3757e493b309f3a5d665e6/lib/staticryptJs.js#L210

Let me know if you guys hit any problem using it, and thanks for the idea! (and final push :pray: )
