### ISSUE TITLE
Encrypt page but with no password prompt box

### ISSUE THREAD

**Issue by g4spow** [robinmoisson/staticrypt#191]
I have been using this product for years, it is absolutely brilliant.

However, one feature I have tried to do with no success is **Encrypt a page with no password prompt box**

I have a simple single HTML page that fetches some price data via a JSON file and displays a single value from it on the page using VueJS. If I don't add a password it encrypts the page and hides the JSON url beautifully (which is perfect as I want this URL which contains the data hidden)
![singlehtmlpage](https://github.com/robinmoisson/staticrypt/assets/14327547/787f01b2-8c04-47c7-8a16-82da09ba7914)

BUT, the user still has to click the Enter button (with no password) to get to my page...
![emptypasswordbox](https://github.com/robinmoisson/staticrypt/assets/14327547/9557b2ba-200c-4736-b98b-d2a572885d1c)

**How can I strip out the password prompt box and just get straight to the newly encrypted page?**

**Comment by oleteacher** [comment]
Search and read the issues, maybe what you need:

https://github.com/robinmoisson/staticrypt/issues/140

**Comment by robinmoisson** [comment]
Hi @g4spow,

Thanks for opening the issue. I think I'm not understanding your situation completely, let me know what I got right: you have an HTML page at a public URL with vue.js that fetches a json file located at a secret URL. You are encrypting the HTML page, so the URL of the JSON file isn't shown when you visit the encrypted HTML public URL.

The password you set for encryption is empty, so anyone who visits the page just has to click on button to decrypt the file. And you'd want for the file to decrypt automatically without any user interaction? This is where I'm a bit lost, why encrypt the file in the first place if it auto-decrypts by itself for everyone - don't you want to just let the HTML file unencrypted then?

Some context on who you want to protect the file from, what type of users you want to be able to see the file and how you are sharing the link might be useful to understand your use case.

Otherwise the couple of blanket suggestions I have would be sharing an [auto-decrypt URL](https://github.com/robinmoisson/staticrypt#get-a-shareable-auto-decrypt-link) as @oleteacher suggested (thanks @oleteacher!), which works with an empty password too, or else having your users check the Remember-me checkbox so it auto-decrypts next times.

Feel free to let me know if that fits the bill for you or if I'm missing something.
