### ISSUE TITLE
Possible to lock folders?

### ISSUE THREAD

**Issue by LebbieTheLuke** [robinmoisson/staticrypt#199]
I was making a github pages site and was looking for a way to lock a entire folder, until the password is entered. Is this possible with staticrypt? thanks.

**Comment by sanbei101** [comment]
你的需求其实只用锁住index.html就可以实现了,不需要锁住文件夹的吧
```
tree .
.
├── assets
│   └── index-p2364_JT.js
├── index.html
└── vite.svg
```

**Comment by robinmoisson** [comment]
So I don't know if that's still relevant to you @LebbieTheLuke - can you detail more what's in your folder?

StatiCrypt can encrypt all html files in your folder (you just have to run `staticrypt -r folder` and it'll be in the `encrypted` folder) - you can check out [the examples](https://github.com/robinmoisson/staticrypt?tab=readme-ov-file#encrypt-multiple-html-files-at-once). The JS and other files won't be encrypted though, so they should not contain any secret information.

Let me know if you have other questions, and I'll close the issue otherwise.

(@sanbei101 google translate tells me your comment is on topic so thanks for that, though let's keep it to English as a common language)

**Comment by robinmoisson** [comment]
Closing, feel free to re-open if needed.
