### ISSUE TITLE
Adding CKEditor to Instructions

### ISSUE THREAD

**Issue by oleteacher** [robinmoisson/staticrypt#21]
Very nice project!

Wanting to use in classroom but users will be 10-12 years old and need to use editor for instructions area.

I have successfully added but submit button is not saving the content from CKEditor. Have failed in many attempts to get working and in hopes you could provide some insight?

This is added in head tags:
`<script src="https://cdn.ckeditor.com/4.7.0/standard/ckeditor.js"></script>`

The textarea looks like this:
`<textarea name="editor1" class="form-control" id="instructions" placeholder="Default: nothing."></textarea>`

With this in footer:
```
<script>
CKEDITOR.replace( 'editor1' );
</script>
```
Any input greatly appreciated.

Susan

**Comment by robinmoisson** [comment]
That's very nice, I'm glad the project can be useful to you ! Out of curiosity, how do you plan on using it in a classroom?

For your issue: CKEditor hides the original textarea and updates it with the formatted HTML it generates on form submission just before sending the data, but since the form is submitted with JS here we need to update it manually.

You can see how to do that on this commit: 03edb5c00f5a73f3c963a7c57dc72371c5d8d5c6 (or you can clone the ckeditor branch where I pushed it). Let me know if that solves your issue !

**Comment by pouringrain0628** [comment]
Nice.

**Comment by pouringrain0628** [comment]
03edb5c

**Comment by oleteacher** [comment]
Thank you for reply Robin.

"Out of curiosity, how do you plan on using it in a classroom?" Mainly for fun. Secret agent stuff:) Just another way to engage bored kids and at same time give them little taste of programming.

I will try the commit and report back with progress.

Thank you again!

**Comment by oleteacher** [comment]
Works great Robin, thanks much.

**Comment by robinmoisson** [comment]
Happy to hear it, have fun in class :)
