### ISSUE TITLE
CSS Styles being stripped out

### ISSUE THREAD

**Issue by oleteacher** [robinmoisson/staticrypt#96]
Really enjoying Staticrypt!

I have experienced an issue when styles like this in page:

`a:link {color: #339999; text-decoration: none}`

The "{color: #339999; text-decoration: none}" is totally stripped from page which results in layout issues. 

When possible, we call the css file from server but in our case final page used on school network and need all css in the final page.

Have looked at:

```
var renderTemplate = function (tpl, data) {
        return tpl.replace(/{(.*?)}/g, function (_, key) {
            return data && data[key] || '';
        });
```
Is it possible to use double {{}} brackets? attempted to change like this but no work:

```
var renderTemplate = function (tpl, data) {
        return tpl.replace(/{{(.*?)}}/g, function (_, key) {
            return data && data[key] || '';
        });
```

Any input greatly appreciated.

**Comment by robinmoisson** [comment]
Hello @oleteacher, I'm glad you're enjoying it !

From what I understand: the problematic CSS is in the `password_template.html` file that you have customized, not in the "secret file" you want to encrypt ?

If so you could change the `renderTemplate` function like this:

    var renderTemplate = function (tpl, data) {
        return tpl.replace(/{(.*?)}/g, function (_, key) {
            return (data && key in data) ? data[key] : '{' + key + '}';
        });
    };

This way: we return `data[key]` if the term inside brackets is a key in our `data` object. If what's inside the brackets is not known (because it's a CSS one-liner, for ex) then we just leave it be.  
Let me know if that helps.

**Comment by oleteacher** [comment]
Perfect @robinmoisson, thank you!

I was stumped and only thing that came to mind was double curly brackets:) Your solution is elegant.
